# -*- coding: utf-8 -*-
"""Face Detection .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5gbAk8RlVT542OQauc_0M-0CACtqOQX
"""

!pip install opencv-python
!pip install opencv-python-headless
!pip install face_recognition

import cv2
from google.colab import files
import matplotlib.pyplot as plt
import numpy as np

# Upload an image file
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Load Haar cascade for face detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Read the image
image = cv2.imread(image_path)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Detect faces
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

# Draw rectangle around faces
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (255, 0, 0), 2)

# Convert image to RGB (for displaying with matplotlib)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Display the image
plt.imshow(image_rgb)
plt.axis('off')
plt.show()